apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: ustc-edu-cn.mirror.aliyuncs.com/kubeguide/tomcat-app:v1
        ports:
        - containerPort: 8080