apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 1jdlp79a.mirror.aliyuncs.com/library/redis:latest
        ports:
        - containerPort: 6379